### PR TITLE
Remove unwanted ~120Kb dependencies

### PR DESCRIPTION
**Pull request by thinker3197**

### CODE REVIEW

**Comment by manojpandey** [comment]
Well played 🐍

**Review by manojpandey — CHANGES_REQUESTED** [review]
kek. Fix merge conflicts now 

ಠ_ಠ

**Comment by thinker3197** [comment]
Noo ❌

**Comment by manojpandey** [comment]
pliss

**Comment by thinker3197** [comment]
Done in [#5](https://github.com/manojpandey/devsoc-matrix/pull/5).

**Pull request closed without merging**
